### ISSUE TITLE
Parsing boundary header fails when boundary string contains equal sign

### ISSUE THREAD

**Issue by hmazter** [goetas/to-swift-mime-parser#1]
When parsing a multipart email that has a boundary that contains a equal sign, the parsing of the boundary header will fail since it explodes on `=` in `MimeParser::extractHeaderParts` (https://github.com/goetas/to-swift-mime-parser/blob/master/lib/Goetas/Mail/ToSwiftMailParser/MimeParser.php#L253)

I've found that by using a limit of 2 in the explode, it will not continue exploding on equal signs except the first one, that is correct.
`list ( $k, $v ) = explode ( "=", trim ( $pv ), 2 );` 

I don't know if i have something wrong in my setup that get boundary strings with equal signs in them.

Example: 

>    boundary="=_0279c8e1ca32bfec4388635cd6ebf613"

**Comment by goetas** [comment]
fixed in https://github.com/goetas/to-swift-mime-parser/commit/a7164a39e047c88891d29c63820f39dbd562e9c1

**Comment by hmazter** [comment]
Nice, thanks for the quick fix!
