### ISSUE TITLE
Undefined variable: nestingLevel

### ISSUE THREAD

**Issue by TerjeBr** [goetas/to-swift-mime-parser#10]
In my behat tests, many are currently failing with this output:
```
        Notice: Undefined variable: nestingLevel in vendor/goetas/to-swift-mime-parser/src/MimeParser.php line 357
```
There seems to be an `if` branch that leaves the variable `$nestingLevel` undefined.

I am using version 2.1.1, git branch 4422efd8aec7e02ecf6d4251f930f4444121a210

**Comment by goetas** [comment]
fixed in https://github.com/goetas/to-swift-mime-parser/pull/13
