### ISSUE TITLE
Symfony 3.4 Cannot instantiate mime parser

### ISSUE THREAD

**Issue by TerjeBr** [goetas/to-swift-mime-parser#5]
When I try to execute `$parser = new \Goetas\Mail\ToSwiftMailParser\MimeParser();` I get this error:

```
 Swift_DependencyException: Cannot lookup dependency "mime.grammar" since it is not registered. in vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php:101
```

**Comment by TerjeBr** [comment]
I am using symfony/swiftmailer-bundle v3.1.6 and swiftmailer/swiftmailer v6.0.2

**Comment by goetas** [comment]
hmmm... never used it with recent symfony versions...

**Comment by TerjeBr** [comment]
Seems that swiftmailer/swiftmailer in version 6.0.0 got merged the PR https://github.com/swiftmailer/swiftmailer/issues/403 that removed the class `Swift_Mime_Grammar`

Is it possible to make this bundle work with swiftmailer/swiftmailer v.6.0 ?
I guess you need to replace the use of `Swift_Mime_Grammar` with something else....

**Comment by goetas** [comment]
cant you downgrade to swiftmailer/swiftmailer  5?

**Comment by TerjeBr** [comment]
Then I get a whole lot of deprecation warnings, that I try to avoid.

Switmailer bundle version 3 requires swiftmailer version 6. Swiftmailer bundle version 2.6.2 does not quite cut it when I want to go with symfony version 3.4

**Comment by goetas** [comment]
:/

**Comment by TerjeBr** [comment]
May be you could make a copy of the class `Swift_Mime_Grammar` that was removed, and use it in the mime parser if it is not found in the swiftmailer registry?

**Comment by TerjeBr** [comment]
Or is it possible for the mime parser to use the egulias/EmailValidator that the swiftmailer uses instead?

**Comment by goetas** [comment]
what about injecting directly the dependencies in the constructor?

**Comment by TerjeBr** [comment]
Which dependencies in which constructor?

**Comment by goetas** [comment]
https://github.com/goetas/to-swift-mime-parser/blob/c9f30ce377a3cd89a420286a0d8c4c9c866984f9/lib/Goetas/Mail/ToSwiftMailParser/MimeParser.php#L17

**Comment by TerjeBr** [comment]
The error happens two lines below when trying to initialize `$this->grammar`

**Comment by TerjeBr** [comment]
The constructor only depends on $allowedHeaders and $removeHeaders

**Comment by goetas** [comment]
the idea is to pass to the constructor the instances of grammar and cache

**Comment by TerjeBr** [comment]
Then it becomes hard to instantiate a mime parser. And if you have swiftmailer/swiftmailer v.6.0 installed you do not have any class `Swift_Mime_Grammar` defined anywhere.

**Comment by TerjeBr** [comment]
You need a convenient factory method to get a mime parser somehow. If it is not the constructor, you will be just shifiting the problem to another place.

**Comment by TerjeBr** [comment]
But I guess if you make the dependencies injected, it does open up the possibillty for me to code around the problem without having to modify your bundle.

**Comment by TerjeBr** [comment]
Made a PR for you: #6

**Comment by goetas** [comment]
tnx, wil have a look at it soon

**Comment by goetas** [comment]
pr was merged
